notional_trading_capital: 1000000
base_currency: "USD"

risk_per_trade_pct_capital: 0.05

trading_rules:
  orion:
     function: private.systems.orion.rules.orion.orion
     data:
         - "rawdata.get_minute_prices"
         - "rawdata.get_sessions"
     other_args:
         big_timeframe: '30 min'
         small_timeframe: '5 min'
         setup_lookback: 50
         rr: 2.5

instrument_weights:
  CL: 1.0

use_SR_costs: False